# Generated by Django 5.2.1 on 2025-05-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseambulancia',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
