# Generated by Django 5.2.1 on 2025-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_alter_baseambulancia_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseambulancia',
            name='type_of_base',
            field=models.CharField(choices=[('INEM', 'INEM'), ('Base Operador', 'Base Operador')], default='INEM', max_length=20),
        ),
    ]
