# Generated by Django 5.2.1 on 2025-05-16 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_incident_type'),
        ('vehicles', '0003_equipment_vehicle_last_maintenance_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('patient_type', models.CharField(choices=[('Doente Não Urgente', 'Doente Não Urgente'), ('Doente Pouco Urgente', 'Doente Pouco Urgente'), ('Doente Urgente', 'Doente Urgente'), ('Doente Muito Urgente', 'Doente Muito Urgente'), ('Doente Emergente', 'Doente Emergente')], default='Doente Não Urgente', max_length=50)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
                ('tripulante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
