# Generated by Django 5.2.1 on 2025-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('Medical', 'Medical'), ('Fire', 'Fire'), ('Accident', 'Accident'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(default='Open', max_length=20)),
            ],
        ),
    ]
