# Generated by Django 5.2.1 on 2025-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_transportrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Atribuído', 'Atribuído'), ('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
