# Generated by Django 5.2.1 on 2025-05-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='bases.baseambulancia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('AdminOperator', 'Operator Administrator'), ('AdminBase', 'Base Administrator'), ('Operador', 'Operator'), ('Pessoal', 'Personnel')], default='Pessoal', max_length=20),
        ),
    ]
