# Generated by Django 5.2.1 on 2025-05-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_alter_baseambulancia_name'),
        ('users', '0004_user_base_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bases.baseambulancia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('AdminOperator', 'Operator Administrator'), ('AdminBase', 'AdminBase'), ('Operador', 'Operator'), ('Pessoal', 'Personnel')], default='Pessoal', max_length=20),
        ),
    ]
