# Generated by Django 5.2.1 on 2025-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_trainingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Operador', 'Operador'), ('Pessoal', 'Pessoal')], default='Pessoal', max_length=20),
        ),
    ]
