# Generated by Django 5.2.1 on 2025-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ambulance', 'Ambulance'), ('Fire Truck', 'Fire Truck'), ('Police Car', 'Police Car')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
