# Generated by Django 5.2.1 on 2025-05-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_alter_baseambulancia_name'),
        ('vehicles', '0007_alter_vehicle_status_alter_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bases.baseambulancia'),
        ),
    ]
