# Generated by Django 5.2.1 on 2025-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Carrinha Ambulancia', 'Carrinha Ambulance'), ('Carro Ambulancia', 'Carro Ambulancia'), ('Helicóptero', 'Helicóptero')], max_length=20),
        ),
    ]
