# Generated by Django 5.2.1 on 2025-05-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('vehicles', '0004_vehicle_base_vehicle_personnel_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bases.baseambulancia'),
            preserve_default=False,
        ),
    ]
