# Generated by Django 5.2.1 on 2025-05-18 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_alter_baseambulancia_name'),
        ('vehicles', '0005_alter_vehicle_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_inspection_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='personnel',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.baseambulancia'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
